---
- hosts: all
  become: yes
  tasks:
    - name: install aws cli v2
      ansible.builtin.shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
