---
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
    - name: Install Packages
      apt:
        update_cache: yes
        pkg: "{{ packages }}"
        state: latest
